
package tpractico5;


public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jmPrincipal = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        mnufAlumno = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        mnuFmateri = new javax.swing.JMenuItem();
        mnuFInscripcion = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 102, 102));
        jDesktopPane1.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jmAlumno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmAlumno.setForeground(new java.awt.Color(255, 102, 102));
        jmAlumno.setText("Alumno");
        jmAlumno.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N

        mnufAlumno.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        mnufAlumno.setForeground(new java.awt.Color(255, 102, 102));
        mnufAlumno.setText("Alta de Alumnos ");
        mnufAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnufAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(mnufAlumno);

        jmPrincipal.add(jmAlumno);

        jmMateria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmMateria.setForeground(new java.awt.Color(255, 102, 102));
        jmMateria.setText("Materia");
        jmMateria.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jmMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMateriaActionPerformed(evt);
            }
        });

        mnuFmateri.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        mnuFmateri.setForeground(new java.awt.Color(255, 102, 102));
        mnuFmateri.setText("Alta de Materias");
        mnuFmateri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFmateriActionPerformed(evt);
            }
        });
        jmMateria.add(mnuFmateri);

        mnuFInscripcion.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        mnuFInscripcion.setForeground(new java.awt.Color(255, 102, 102));
        mnuFInscripcion.setText("Formulario de Inscripcion");
        jmMateria.add(mnuFInscripcion);

        jmPrincipal.add(jmMateria);

        jmSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmSalir.setForeground(new java.awt.Color(255, 102, 102));
        jmSalir.setText("SALIR");
        jmSalir.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jmPrincipal.add(jmSalir);

        setJMenuBar(jmPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuFmateriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFmateriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuFmateriActionPerformed

    private void mnufAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnufAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnufAlumnoActionPerformed

    private void jmMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmMateriaActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenuBar jmPrincipal;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem mnuFInscripcion;
    private javax.swing.JMenuItem mnuFmateri;
    private javax.swing.JMenuItem mnufAlumno;
    // End of variables declaration//GEN-END:variables
}
