
package vistasTp5;


public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jmPrincipal = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmiAltaAlumno = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmiAltaMateria = new javax.swing.JMenuItem();
        jmiFormularioInscripcion = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(255, 102, 102));
        escritorio.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jmAlumno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmAlumno.setForeground(new java.awt.Color(255, 102, 102));
        jmAlumno.setText("Alumno");
        jmAlumno.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N

        jmiAltaAlumno.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jmiAltaAlumno.setForeground(new java.awt.Color(255, 102, 102));
        jmiAltaAlumno.setText("Alta de Alumnos ");
        jmiAltaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAltaAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiAltaAlumno);

        jmPrincipal.add(jmAlumno);

        jmMateria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmMateria.setForeground(new java.awt.Color(255, 102, 102));
        jmMateria.setText("Materia");
        jmMateria.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N

        jmiAltaMateria.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jmiAltaMateria.setForeground(new java.awt.Color(255, 102, 102));
        jmiAltaMateria.setText("Alta de Materias");
        jmiAltaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAltaMateriaActionPerformed(evt);
            }
        });
        jmMateria.add(jmiAltaMateria);

        jmiFormularioInscripcion.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jmiFormularioInscripcion.setForeground(new java.awt.Color(255, 102, 102));
        jmiFormularioInscripcion.setText("Formulario de Inscripcion");
        jmiFormularioInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioInscripcionActionPerformed(evt);
            }
        });
        jmMateria.add(jmiFormularioInscripcion);

        jmPrincipal.add(jmMateria);

        jmSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmSalir.setForeground(new java.awt.Color(255, 102, 102));
        jmSalir.setText("SALIR");
        jmSalir.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        jmPrincipal.add(jmSalir);

        setJMenuBar(jmPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAltaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAltaMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioDeMaterias fdm=new FormularioDeMaterias();
        fdm.setVisible(true);
        escritorio.add(fdm);
    }//GEN-LAST:event_jmiAltaMateriaActionPerformed

    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jmSalirMouseClicked

    private void jmiFormularioInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioInscripcionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
       FormularioDeInscripcion fdi = new FormularioDeInscripcion();
        fdi.setVisible(true);
        escritorio.add(fdi);
    }//GEN-LAST:event_jmiFormularioInscripcionActionPerformed

    private void jmiAltaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAltaAlumnoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioDeAlumnos fda = new FormularioDeAlumnos();
        fda.setVisible(true);
        escritorio.add(fda);
    }//GEN-LAST:event_jmiAltaAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenuBar jmPrincipal;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAltaAlumno;
    private javax.swing.JMenuItem jmiAltaMateria;
    private javax.swing.JMenuItem jmiFormularioInscripcion;
    // End of variables declaration//GEN-END:variables
}
